#!/bin/sh

if [ -z "$1" ]; then
  echo "Usage: bm++ <file_path>"
  exit 1
fi

case $(uname -s) in
  Linux)
    g++ -std=c++20 -O2 -fsanitize=signed-integer-overflow $1 -o ${1%.*}
    ;;
  Darwin)
    g++ -std=c++20 -O2 -fsanitize=signed-integer-overflow -Wl,-stack_size -Wl,20000000 -include-pch bits/stdc++.h.gch $1 -o ${1%.*}
    ;;
  *)
    g++ -std=c++20 -O2 $1 -o ${1%.*}
    ;;
esac

